### ISSUE TITLE
Does not work in VM with Ubuntu 18.04.04: Pool overlaps with other one

### ISSUE THREAD

**Issue by krisk0** [hassiweb/docker-open5gs#1]
On one machine, I have dockerd. On another machine, I have virtualbox with virtual machine (VM) running Ubuntu 18.04.04. Both computers run Gentoo Linux. In the VM, I disabled dockerd and set DOCKER_HOST properly. **docker images** shows images on my server as expected.

**docker-compose up** aborts immediately saying
```
Creating network "dockeropen5gs_core_network" with driver "bridge"
Pool overlaps with other one on this address space
```
Removing interface with address 192.168.26.1/24 on dockerd server and changing .26. to .27. in **docker-compose.yml** does not help. **ip a** does not show any interface in 192.168.26.1/24 or 192.168.27.1/24 address space (on any of the 3 computers).

docker version: 19.03.13-r2 server, 17.12.1-ce build 7390fc6 client.

I am new to Docker. I would like to understand what is happening and solve the matter. I need to start Open5gs core and will appreciate any help.

**Comment by hassiweb** [comment]
If you have created a docker network so far using the `docker-compose` command, there would be a zombie of the network.
In this case, you can delete all resources defined in `docker-compose.yml` with the command below:
```
docker-compose down
```

or you can delete the network only with the command below:
```
docker network prune
```

Let's try this first!

Thanks!!

**Comment by krisk0** [comment]
docker-compose failed with message '... not found'.

docker network prune did the job.

Thank you.

Directory **config** does not mount (seen as empty inside container). So containers don't work. Is it at all possible to run them on a machine not running docker server?

**Comment by krisk0** [comment]
Closing the issue as suggested by @hassiweb
